---
# Source: bitcoin-core/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitcoin-core
  labels:
    app.kubernetes.io/name: bitcoin-core
    helm.sh/chart: bitcoin-core-1.1.4
    app.kubernetes.io/instance: bitcoin-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: bitcoin-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bitcoin-core
subjects:
  - kind: ServiceAccount
    name: bitcoin-core
    namespace: "sre-workflow"
