---
# Source: bitcoin-core/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-core
  namespace: "sre-workflow"
  labels:
    app.kubernetes.io/name: bitcoin-core
    helm.sh/chart: bitcoin-core-1.1.4
    app.kubernetes.io/instance: bitcoin-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: bitcoin-core
data:
  bitcoin.conf:
    |
      server=1
      txindex=1
    
      chain=main
      # chain=test
      # chain=regtest
      # chain=signet
    
      rpcserialversion=0
      rpcuser=hirosystems
      rpcpassword=hirosystems
    
      rpcallowip=192.168.0.0/20
      rpcallowip=10.0.0.0/16
      whitelist=192.168.0.0/20
      whitelist=10.0.0.0/16
      rpcbind=0.0.0.0
    
      dbcache=75
      maxorphantx=10
      maxmempool=150
      nodebuglogfile=1
