---
# Source: bitcoin-core/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitcoin-core
  namespace: "sre-workflow"
  labels:
    app.kubernetes.io/name: bitcoin-core
    helm.sh/chart: bitcoin-core-1.1.4
    app.kubernetes.io/instance: bitcoin-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: bitcoin-core
spec:
  rules:
    - host: bitcoin-core.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bitcoin-core
                port:
                  name: http-rpc
  tls:
    - hosts:
        - "bitcoin-core.local"
      secretName: bitcoin-core.local-tls
