---
# Source: bitcoin-core/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-core
  namespace: "sre-workflow"
  labels:
    app.kubernetes.io/name: bitcoin-core
    helm.sh/chart: bitcoin-core-1.1.4
    app.kubernetes.io/instance: bitcoin-core
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: bitcoin-core
spec:
  replicas: 3
  podManagementPolicy: "OrderedReady"
  selector:
    matchLabels: 
      app.kubernetes.io/name: bitcoin-core
      app.kubernetes.io/instance: bitcoin-core
      app.kubernetes.io/component: bitcoin-core
  serviceName: bitcoin-core
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitcoin-core
        helm.sh/chart: bitcoin-core-1.1.4
        app.kubernetes.io/instance: bitcoin-core
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: bitcoin-core
    spec:
      serviceAccountName: bitcoin-core
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: bitcoin-core
                    app.kubernetes.io/instance: bitcoin-core
                    app.kubernetes.io/component: bitcoin-core
                namespaces:
                  - "sre-workflow"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: bitcoin-core
          image: sre-workflow:latest
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/hirosystems/config/bitcoin.conf
          env:
            - name: BITCOIN_DATA
              value: /hirosystems/data/.bitcoin
          envFrom:
          resources:
            limits: {}
            requests: {}
          ports:
            - name: http-rpc
              containerPort: 8332
            - name: tcp-p2p
              containerPort: 8333
          volumeMounts:
            - name: data
              mountPath: /hirosystems/data
              readOnly: false
            - name: config
              mountPath: /hirosystems/config
      volumes:
        - name: config
          configMap:
            name: bitcoin-core
        - name: data
          emptyDir: {}
